### ISSUE TITLE
Ability for the system to keep track of user's purchase history

### ISSUE THREAD

**Issue by Tyndallray** [Shoporama-Cent/comp313-002-Team4-shoporama-backend#17]

**Comment by Tyndallray** [comment]
After #15

**Comment by despean** [comment]
We can pull this out from strip account because it stores customer transaction
or we can track it seperately, what do you think?

**Comment by Tyndallray** [comment]
Oh, If there is an ability to do it from stripe, then it will make our lives much easier. When we reach implementation of this thing, lets discuss. Because, I believe we will have to create customer cart, and order functionality before that, or don't we?
